clips = %w(
ImportantTardyWebNotLikeThis
OpenLivelySardineThunBeast
DirtyArborealTroutVoteYea
RelatedAdventurousFishFloof
UnsightlyAnimatedAirGuitarMau5
EmpathicEmpathicSalsifyHotPokket
ObedientHappyWhaleKlappa
RudeZealousFlySquadGoals
OilyDignifiedPoxDansGame
AdventurousCharmingBoarTakeNRG
SmilingConcernedSlothShazBotstix
CulturedSpikyDragonRedCoat
ElatedManlySkunkPRChase
ColdbloodedSuperPeafowlDoubleRainbow
AgileResoluteLadiesTakeNRG
BreakableHandsomeVampireChocolateRain
EmpathicDelightfulFlamingoTTours
ArtisticTardyOkapiTTours
AssiduousViscousQueleaThisIsSparta
InspiringElegantTortoiseTooSpicy
PricklyBlatantWerewolfDendiFace
ClumsyTangibleElkDogFace
PluckyOilyShrimpResidentSleeper
SecretiveLazyVelociraptorBCWarrior
NimbleModernNuggetsLitFam
KindAmorphousCrabsBudBlast
ConcernedSmellyWaterKlappa
PrettiestFamousStrawberryPeteZaroll
ThoughtfulBovineFriseeKippa
ComfortableBlindingPistachioNerfBlueBlaster
NiceHonorableGuanacoFloof
ZealousBlazingJalapenoSpicyBoy
CarefulLivelyDadBCouch
HelplessProtectiveCocoaLitty
CuriousFinePeanutSeemsGood
SucculentImpossiblePizzaDansGame
IgnorantWanderingRaccoonPeoplesChamp
BigDirtyHawkPanicVis
BombasticZealousSushiBlargNaut
LachrymoseRepleteAniseCmonBruh
ComfortableAcceptableHamburgerRitzMitz
DiligentTenuousTriangleRlyTho
CuteGentleLemurBloodTrail
HomelyRefinedScorpionWTRuck
ElatedGenerousSandpiperHotPokket
CharmingCheerfulDootGingerPower
BovineSarcasticRedpandaYouDontSay
CrowdedRacyGnatTF2John
ArborealCrepuscularRhinocerosKappa
IronicApatheticPineappleDBstyle
EasySolidWombatHassaanChop
ClumsyOilyLadiesCoolStoryBro
SmallSincereElephantCharlietheUnicorn
WittyTiredElkJonCarnage
DeafApatheticWolfBuddhaBar
BlueRamshackleNuggetsTF2John
CoyGleamingChickpeaBCWarrior
DiligentInventiveDurianBuddhaBar
BrainyDelightfulPorpoiseBatChest
WittyDeadStingrayOSkomodo
CreativeBumblingEyeballBCWarrior
OriginalGoodAdminRickroll
OddBetterCrabTBTacoRight
ObservantAnnoyingButterRickroll
SingleShakingBorkTBTacoRight
RenownedBlightedSheepSmoocherZ
SpeedyFaintElkPermaSmug
ResilientTransparentPizzaShazBotstix
BlueRamshackleNuggetsTF2John
RamshackleSecretiveSandpiperRickroll
ObedientHappyWhaleKlappa
RudeZealousFlySquadGoals
DeafApatheticWolfBuddhaBar
ArtisticSwissRedpandaDxAbomb
CogentIgnorantMuleTBCheesePull
PeacefulGiantKittenTheRinger
EmpathicEmpathicSalsifyHotPokket
RelatedAdventurousFishFloof
InquisitiveProtectiveWalletPraiseIt
CourteousSparklyCobblerKevinTurtle
RespectfulPlainZucchiniAllenHuhu
ImportantTardyWebNotLikeThis
YummyAbrasiveHorseradishDBstyle
TangibleCallousShrimpStrawBeary
SwissThankfulAppleBrokeBack
OpenCourageousStinkbugPlanking
VictoriousConsiderateClamDendiFace
ElatedTacitKathyPJSalt
SullenFrailClipzGOWSkull
SpeedyLuckyAniseJonCarnage
ChillyBeautifulWaterWholeWheat
ZanyHeartlessArmadilloArgieB8
AverageMagnificentKathyFloof
KathishHelpfulPheasantPRChase
ChillyDeterminedWitchM4xHeh
MistyBillowingNeanderthalPlanking
AbrasivePoisedCucumberSmoocherZ
TangentialSlickUdonRalpherZ
TriumphantCleverWitchAMPTropPunch
FitArbitraryLyrebirdCharlietheUnicorn
FancyTacitPepperBrainSlug
KitschyTriangularChipmunkKlappa
PoisedVictoriousVanillaMcaT
DeliciousMoistCheddarUWot
TacitRamshackleBulgogiBudStar	
).select{|c| !c.strip.empty?}

WORKER_CNT = 2

def spawn_automata(_clips, worker_id=0)
	_clips.each do |clip|
		cmd = "python3 sample_automata.py -c #{clip} #{ARGV[0] == '-n' ? '-n' : '-y'}"
		puts "[Worker #{worker_id}]: #{cmd}"
		system(cmd)
	end
end

n = clips.size
queues = Array.new(WORKER_CNT){|i| clips[i*n/WORKER_CNT...(i+1)*n/WORKER_CNT]}
threads = []
WORKER_CNT.times do |i|
	threads << Thread.new{spawn_automata(queues[i], i)}.run
end
threads.each{|th| th.join}
